package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'UnitTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("UnitTests")) {
    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "credentialsJSON:7b4ae65b-efad-4ea8-8ddf-b48502524605"
                    }
                }
                param("github_oauth_user", "hsz")
            }
        }
        feature1.apply {
            vcsRootExtId = "${DslContext.settingsRoot.id}"
            publisher = github {
                statusCheckName = ""
                githubUrl = "https://api.github.com"
                authType = storedToken {
                    tokenId = "tc_token_id:CID_7bac63521d33dff346806a0a72c1f875:-1:ba01b8a4-a359-4c95-9d14-e301420110b1"
                }
            }
            param("secure:github_access_token", "")
            param("github_oauth_user", "")
        }
    }
}
