property ::= (KEY? SEPARATOR VALUE?) | KEY {
  mixin = "org.jetbrains.grammarkit.psi.impl.SimpleNamedElementImpl"
  implements = "org.jetbrains.grammarkit.psi.SimpleNamedElement"
  methods = [getKey getValue getName setName getNameIdentifier]
}
