name: Nightly Release (scheduled)

# Automatically run the release-nightly job
#
# The scheduled release will be disabled on forks, preventing unnecessary work.

on:
  schedule:
    - cron: "0 0 * * *"

jobs:

  release-nightly:
    if: contains('JetBrains/intellij-platform-gradle-plugin', github.repository)
    uses: ./.github/workflows/release-nightly.yml
    secrets: inherit
