name: Reusable Unit Tests

on: [ workflow_call ]

jobs:
  unitTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    uses: ./.github/workflows/reusable-single-unitTest.yml
    secrets: inherit
    permissions:
      checks: write
    with:
      gradleVersion: ${{ matrix.gradleVersion }}
      os: ${{ matrix.os }}
      cacheReadOnly: true

    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - "9.0.0"
          - "9.5.0"
          - "nightly"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
