name: Reusable Integration Tests

on:
  workflow_call:
    inputs:
      platformVersion:
        required: false
        default: 2022.1.4
        type: string
      testName:
        required: false
        default: ""
        type: string

jobs:
  integrationTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - "9.0.0"
          - "9.5.0"
          - "nightly"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:

      # Free GitHub Actions Environment Disk Space
      - name: Maximize Build Space
        if: runner.os == 'Linux'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Restore IntelliJ Platform test cache
        id: intellij-platform-cache
        uses: actions/cache/restore@v5
        with:
          path: .gradle/testGradleHome/.intellijPlatform
          key: test-gradle-home-v5-intellij-platform-${{ runner.os }}-${{ hashFiles('gradle.properties', 'build.gradle.kts', 'gradle/libs.versions.toml', 'src/test/**/*.kt', 'src/test/resources/**', 'src/testFixtures/**/*.kt', 'src/integrationTest/**/*.kt', 'src/integrationTest/resources/**') }}
          restore-keys: |
            test-gradle-home-v5-intellij-platform-${{ runner.os }}-

      - name: Restore Gradle TestKit cache
        uses: actions/cache/restore@v5
        with:
          path: .gradle/testGradleHome/.testKit
          key: test-gradle-home-v1-testkit-${{ runner.os }}-${{ matrix.gradleVersion }}-${{ hashFiles('gradle.properties', 'build.gradle.kts', 'gradle/libs.versions.toml') }}
          restore-keys: |
            test-gradle-home-v1-testkit-${{ runner.os }}-

      - name: Run Tests
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          TEST_NAME: ${{ inputs.testName }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            TEST_GRADLE_USER_HOME="$(pwd -W)\\.gradle\\testGradleHome"
          else
            TEST_GRADLE_USER_HOME="$PWD/.gradle/testGradleHome"
          fi
          TESTS=()
          if [ -n "$TEST_NAME" ]; then
            TESTS+=(--tests "$TEST_NAME")
          fi

          ./gradlew integrationTest \
            -PtestGradleVersion="${{ matrix.gradleVersion }}" \
            -PtestGradleUserHome="$TEST_GRADLE_USER_HOME" \
            "${TESTS[@]}" \
            --console=plain \
            --no-build-cache
