name: Reusable Unit Tests

on: [ workflow_call ]

jobs:
  primeUbuntuIntellijPlatformTestCache:
    uses: ./.github/workflows/reusable-prime-intellij-platform-test-cache.yml
    secrets: inherit
    with:
      gradleVersion: "9.4.0"
      os: ubuntu-latest

  primeWindowsIntellijPlatformTestCache:
    uses: ./.github/workflows/reusable-prime-intellij-platform-test-cache.yml
    secrets: inherit
    with:
      gradleVersion: "9.4.0"
      os: windows-latest

  primeMacosIntellijPlatformTestCache:
    uses: ./.github/workflows/reusable-prime-intellij-platform-test-cache.yml
    secrets: inherit
    with:
      gradleVersion: "9.4.0"
      os: macos-latest

  unitTests:
    name: Gradle ${{ matrix.gradleVersion }} @ ${{ matrix.os }}
    needs:
      - primeUbuntuIntellijPlatformTestCache
      - primeWindowsIntellijPlatformTestCache
      - primeMacosIntellijPlatformTestCache
    uses: ./.github/workflows/reusable-single-unitTest.yml
    secrets: inherit
    permissions:
      checks: write
    with:
      gradleVersion: ${{ matrix.gradleVersion }}
      os: ${{ matrix.os }}
      cacheReadOnly: true

    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - "9.0.0"
          - "9.4.0"
          - "nightly"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
